[tool.poetry]
name = "sevenfield-bot"
version = "0.1.0"
description = ""
authors = ["Zeithrold <zeithrold@gmail.com>"]
readme = "README.md"
packages = [{include = "sevenfield_bot"}]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc2"
uvicorn = "^0.20.0"
ghapi = "^1.0.3"
pony = "^0.7.16"
pymysql = "^1.0.2"
nonebot-adapter-onebot = "^2.2.0"
nonebot-adapter-github = "^0.2.5"
nonebot-plugin-status = "^0.6.0"
fastapi = "^0.89.1"
websockets = "^10.4"
nonebot-plugin-apscheduler = "^0.2.0"
openaiauth = {git = "https://github.com/acheong08/OpenAIAuth.git", rev = "66db9f9c8df7457195fb555c7dc1aded8963d5bc"}
nonebot-plugin-chatgpt = {git = "https://github.com/zeithrold/nonebot-plugin-chatgpt.git", rev = "master"}

[tool.nonebot]
plugins = ["nonebot_plugin_status", "nonebot_plugin_apscheduler", "nonebot_plugin_chatgpt"]
plugin_dirs = ["sevenfield_bot/plugins"]

[tool.poetry.group.dev.dependencies]
nb-cli = "^0.6.9"
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
